### ISSUE TITLE
GTX file gets renamed with a "2" and Bfres Tool fails to recognize it.

### ISSUE THREAD

**Issue by BryAlrighty** [aboood40091/BFRES-Tool#1]
In certain Breath of the Wild items I've tried to open (after converting sbfres to bfres), it will start extracting DDS files, but suddenly stop.

![desktop 08 10 2017 - 16 48 37 02](https://user-images.githubusercontent.com/30912086/29193744-332ffb9e-7dec-11e7-818e-334d2a594c6a.png)

![desktop 08 10 2017 - 16 48 45 03](https://user-images.githubusercontent.com/30912086/29193762-4657a01e-7dec-11e7-83ad-fb1d46d05a0a.png)

Then I notice there is a GTX file after the DDS ones.  It's the file it said could not be found.  The reason is that it adds a "2" to the end of the file name.  So it would be "filename2.gtx" instead of "filename.gtx" like it's supposed to be.

![desktop 08 10 2017 - 16 48 57 04](https://user-images.githubusercontent.com/30912086/29193767-4adf945c-7dec-11e7-83fd-f7b70607e4d7.png)

To fix it, I simply rename the file without the "2" in it and open bfres tool again and it works fine.

Just curious if you could fix this issue for quicker extraction, thanks!

**Comment by aboood40091** [comment]
The problem is that TexConv2 simply doesn't recognize the GTX file for unknown reasons.

I might fix this issue in the future, but for now, use Wexos's Toolbox:
wiki.tockdom.com/wiki/Wexos%27s_Toolbox

**Comment by BryAlrighty** [comment]
Wexo's toolbox only recognizes certain files in botw.  The files that include models work fine (.sbfres).  But textures are seperated into .tex1.sbfres and .tex2.sbfres which are not recognized by the toolbox, even if you convert them to bfres first.

![desktop 08 11 2017 - 09 51 23 01](https://user-images.githubusercontent.com/30912086/29218577-db8a6b06-7e7a-11e7-84ca-d1c6d3eafbf1.png)
![desktop 08 11 2017 - 09 51 29 02](https://user-images.githubusercontent.com/30912086/29218576-db850de6-7e7a-11e7-82c3-5489a775b714.png)
(Same error even if I convert to bfres first)

Your bfres tool seems to recognize them though.

Also, the GTX file works fine after it gets renamed without the "2" so maybe you could just add it to detect file names with a "2" at the end of them, and have it automatically rename it.. for instance "filename2.gtx becomes "filename.gtx" and then it'll be fine.

**Comment by aboood40091** [comment]
The name isn't the problem.
You see, the one with the "2" is supposed to by passed to TexConv2, and TexConv2 will create a one without "2". Then the one without the "2" would be passed to my GTX Extractor, which will convert it to DDS.

In this case here, TexConv2 didn't recognize the one with the "2", for unknown reasons. And since TexConv2 didn't recognize it, the one without the "2" won't be created, and since that won't be created, my GTX Extractor won't be able to convert to DDS.

I will probably fix this soon anyway.

**Comment by BryAlrighty** [comment]
Oh that could explain something else important then.. after I rename it to get rid of "2" and extract the DDS from it.  Then replace the DDS and reinject.  The texture in the game is super glitched.

So we end up having to inject it into a working DDS in another bfres file, then pull the imagedata from hex and replace it where we want the texture to go.  

So that explains why the injection process on these specific DDS files messes up I guess.

Anyway, thank you for the information! Good luck with resolving the issue whenever you have time.

**Comment by aboood40091** [comment]
I found the problem. Tex1 BFRES files don't store mipmaps (they are in Tex2 BFRES files), so, TexConv2 tries to search for mipmaps, but doesn't find them.

I just updated BFRES Tool. While it's true that the textures, which you weren't able to extract before, will extract now, but you will have to either add the mipmaps to the DDS after extracting, or set the number of mipmaps in the DDS header to 1. If you don't, you won't be able to open the DDS file.

**Comment by BryAlrighty** [comment]
So basically, in paint.net, save without mips?  The mips are in tex2 bfres anyway, so thats why it doesn't have them in tex1.  So saving without mips should do it.  Typically DXT1 with no mipmaps.

Thanks for finding the problem!  Can't wait for the release build. *thumbs up*

**Comment by aboood40091** [comment]
Well, yes, I forgot to tell you that you have to save without mips. 
But what I meant is that when you EXTRACT a Tex1 BFRES, some DDS files won't open, because the mips are missing/corrupted. What you need to do to open those DDS files is to edit the header of the DDS file and change the number of mips to 1.

**Comment by BryAlrighty** [comment]
Oh yea I've had some of those before.. had no idea why they wouldn't open.

How do you modify the header? Quick hex edit?

**Comment by aboood40091** [comment]
Yes, change the byte 0x1C to 01.
