### ISSUE TITLE
Broken textures after injecting into the game

### ISSUE THREAD

**Issue by GritPixel** [aboood40091/BFRES-Tool#2]
So, I used the latest version of your BFRES tool (4.1)  to dump the textures from 1-1 of SM3DW (EnterCatMarioTexture.szs). I extracted the .bfres and then I opened it up in your tool. It dumped the .dds files with no problem. I then replaced "Lawn00_DM_alb" (9 mipmaps and in the BC1/DXT1 format) with my modified .dds file. It injected it with no problem. I compressed back into .szs and then loaded it up in the game. Everything was chopped up and garbled. At first I thought my modified .dds file was not saved right or something like that. So I used your tool again but instead of injecting my modified .dds file I used the same .dds file your tool outputted. I saved it compressed it and then I got the same thing in the game.

![output](https://user-images.githubusercontent.com/27905153/29580863-5252a064-872c-11e7-9926-bd406e5dc601.PNG)

Do you want me to upload the modified .bfres file?

**Comment by aboood40091** [comment]
Upload the original SZS and modified SZS.

**Comment by GritPixel** [comment]
Ok here you go:

[files.zip](https://github.com/aboood40091/BFRES-Tool/files/1243283/files.zip)

**Comment by aboood40091** [comment]
This is not an issue in BFRES Tool, it's an issue in your SZS file.

I'll be nice enough and point it out, change byte 0A from 00 to 20, like this:
![image](https://user-images.githubusercontent.com/10743814/29589770-970574ae-87a7-11e7-8ff0-065fa631d995.png)
![image](https://user-images.githubusercontent.com/10743814/29589781-a747198a-87a7-11e7-869c-68bb4ce5fe1b.png)

**Comment by GritPixel** [comment]
Changing the header did not solve the problem, however I re dumped the game and I got custom textures working with wexos toolbox. I then tried your tool and it worked as well. Thank you for your help. 😀 

![thanks](https://user-images.githubusercontent.com/27905153/29594201-4424e528-8764-11e7-812a-62b278e5f96c.PNG)

**Comment by aboood40091** [comment]
Oh well.

Congratulations on getting it to work.
