### ISSUE TITLE
Replacing files without UI?

### ISSUE THREAD

**Issue by BranWar** [aboood40091/BFRES-Tool#3]
Hey! I was wondering if there's any way to replace files using cmd or another way instead of opening the tool, selecting the file you want to use, select the new file to replace it, and repeat. For all I know, I could be using it wrong, so mind my potential ignorance. I feel like this would be nice to be able to replace multiple files with.

**Comment by aboood40091** [comment]
It's in my to-do list for the next version.

**Comment by BranWar** [comment]
Oh, ok. Awesome! Don't mean to seem like an impatient jerk, but do you have an idea of when that'd be? I'm working on a fairly lengthy project using your tool and I didn't know if I should just continue with it or just wait.

**Comment by aboood40091** [comment]
It would take a few days, to be honest.
I have my hands full with other stuff as well.

**Comment by aboood40091** [comment]
Added scanning directories for DDS files.
